sudo: false
language: python
env:
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-djdev

  - TOXENV=py32-dj16
  - TOXENV=py32-dj17
  - TOXENV=py32-dj18

  - TOXENV=py33-dj16
  - TOXENV=py33-dj17
  - TOXENV=py33-dj18

  - TOXENV=py34-dj17
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-djdev

  - TOXENV=py35-dj19
  - TOXENV=py35-djdev

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV="py27-djdev"
    - env: TOXENV="py32-dj16"
    - env: TOXENV="py32-dj17"
    - env: TOXENV="py32-dj18"
    - env: TOXENV="py34-djdev"
    - env: TOXENV="py35-dj19"
    - env: TOXENV="py35-djdev"

install:
  - pip install --upgrade pip tox

script:
  - tox

branches:
  only:
    - master

notifications:
  email: false
