sudo: false
language: python
env:
  - TOXENV=py27-dj1.8
  - TOXENV=py27-dj1.9
  - TOXENV=py27-dj1.10
  - TOXENV=py27-dj.dev

  - TOXENV=py34-dj1.8
  - TOXENV=py34-dj1.9
  - TOXENV=py34-dj1.10
  - TOXENV=py34-dj.dev

  - TOXENV=py35-dj1.9
  - TOXENV=py35-dj1.10
  - TOXENV=py35-dj.dev

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV="py27-dj.dev"
    - env: TOXENV="py34-dj.dev"
    - env: TOXENV="py35-dj1.9"
    - env: TOXENV="py35-dj.dev"

install:
  - pip install --upgrade pip tox

script:
  - tox

branches:
  only:
    - master

notifications:
  email: false
